#! /usr/bin/env python
################################################################################
# This script is written by Pavel Bashtrykov
# pavel.bashtrykov@ibtb.uni-stuttgart.de
# pavel.bashtrykov@gmail.com
################################################################################


import argparse

from utils.barplot import SimpleBarplot
from utils.heatmap import SimpleHeatmapMaker
from utils.plotmaker import make_plot
from utils.readers import ComputeFlanksCSVReader, PreferenceFileCSVReader, read_input
from utils.scatterplot import SimpleScatterplot


def main():
    # parameters
    parser = argparse.ArgumentParser()
    parser.add_argument("--infile", nargs="+", help="Input file(s) containing flanks data, generated by \"computeFlanks.py\"", required=True)
    parser.add_argument("--comparison", type=str, help="File containing flanks preferences for comparison (DNMTs, TETs, etc.)", required=True)
    args = parser.parse_args()


    datafiles = args.infile
    comparison = args.comparison

    print(f"{datafiles=}")
    print(f"{comparison=}")

    # storage1 = read_input(datafiles[0], ComputeFlanksCSVReader())
    # storage2 = read_input(comparison, ComputeFlanksCSVReader())
    # make_plot(storage1.data[0], storage2.data[0], SimpleHeatmapMaker())
    # make_plot(storage1.data[2], storage2.data[2], SimpleScatterplot())
    # make_plot(storage1.data[0], storage2.data[0], SimpleBarplot())

    storage1 = read_input(datafiles[0], ComputeFlanksCSVReader())
    storage2 = read_input(comparison, PreferenceFileCSVReader())


if __name__=="__main__":
    main()