#! /usr/bin/env python3.10
################################################################################
# This script is written by Pavel Bashtrykov
# pavel.bashtrykov@ibtb.uni-stuttgart.de
# pavel.bashtrykov@gmail.com
################################################################################

import argparse


def main():
    # paramethers of the run
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--infile", help="Input file", type=str, required=True)
    parser.add_argument(
        "-b", "--bmap", help="Methylation report generated by BMap", action="store_true"
    )
    parser.add_argument("-o", "--outfile", help="Output file", type=str)
    args = parser.parse_args()

    infile = args.infile
    savein = args.outfile if args.outfile else "coordinates.bed"

    # main part
    with open(infile, "r") as fh, open(savein, "w") as s:

        line = fh.readline()
        while line:
            data = line.split()
            if (
                int(data[3]) > 0 or int(data[4]) > 0
            ):  # check if this C is covered in sequencing
                if data[2] == "-":
                    data = _get_minus_strand_coordinates(data)
                else:
                    data = _get_plus_strand_coordinates(data)
                if not args.bmap:
                    # if this is a BMap report, keeps mC and total counts
                    # if this is a Bismark report
                    # replace unmethylated cytosine count by sum of methylated + unmethylated = total counts
                    try:
                        data[5] = str(int(data[4]) + int(data[5]))
                    except:
                        data = None
                # merge last columns of methylation report in one string
                if data:
                    name = ";".join(data[4:])
                    data.insert(3, name)  # add "name field" bed file
                    data.insert(4, str(0))  # add 0 score field bed file
                    s.write("\t".join(data[:6]))
                    s.write("\n")
            line = fh.readline()

def _get_plus_strand_coordinates(indata: list) -> list | None:
    """Takes one line of methylation report as a list, gets a cytosine coordinate,
	converts to 0 base coordinate, adds the next base coordinate, and adds 10 bases around this central CN dinucleotide.
	
	Parameters
	----------
	indata : list, elements of one line from methylation report

	Returns
	-------
	indata : list, with a new start coordinate and an end coordinate
		Coordinates correspond to 22 nucleotide seqeunce with the central CN dinucleotide.
	"""
    # calculate the start coordinate to 0 base add -10 flank
    start = int(indata[1]) - 1 - 10
    if start < 0:
        return None
    else:
        # update the start coordinate to 0 base add -10 flank
        indata[1] = str(start)
        # add the end coordinate to make CN+-10 nucleotides
        indata.insert(2, str(start + 22))
        return indata

def _get_minus_strand_coordinates(indata: list) -> list | None:
    """Takes one line of methylation report as a list, gets a cytosine coordinate,
	converts to 0 base coordinate, adds the next base coordinate, and adds 10 bases around this central CN dinucleotide.
	
	Parameters
	----------
	indata : list, elements of one line from methylation report

	Returns
	-------
	indata : list, with new start coordinate and end coordinate
		Coordinates correspond to 22 nucleotide seqeunce with the central CN dinucleotide.
	"""
    # calculate the start coordinate to 0 base, add -1 for CN, add -10 for flank
    start = int(indata[1]) - 1 - 1 - 10
    if start < 0:
        return None
    else:
        # update the start coordinate to 0 base add -10 flank
        indata[1] = str(start)
        # add the end coordinate to make CN+-10 nucleotides
        indata.insert(2, str(start + 22))
        return indata


if __name__ == "__main__":
    main()
